name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-22.04
    container: pspdev/pspdev:latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        apk add zip

    - name: Checkout dbglogger
      uses: actions/checkout@v4
      with:
        repository: bucanero/dbglogger
        path: dbglogger

    - name: Install dbglogger
      working-directory: dbglogger
      run: |
        make -f Makefile.psp install

    - name: Build PKGi App Package (OFW)
      run: |
        mkdir ofw && cd ofw
        psp-cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_PRX=ON -DENC_PRX=ON
        make
        make createzip

    - name: Build PKGi App Package
      run: |
        psp-cmake . -DCMAKE_BUILD_TYPE=Release
        make
        make createzip
    
    - name: Get short SHA
      id: slug
      run: |
        printf '%s\n' "sha8=$(printf '%s\n' ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

    - name: Push package artifact
      uses: actions/upload-artifact@v4
      with:
        name: pkgi-psp-build_${{ steps.slug.outputs.sha8 }}
        path: pkgi-psp.zip
        if-no-files-found: error

    - name: Push OFW artifact
      uses: actions/upload-artifact@v4
      with:
        name: pkgi-ofw-build_${{ steps.slug.outputs.sha8 }}
        path: ofw/pkgi-psp.zip
